### ISSUE TITLE
Simplify content contribution

### ISSUE THREAD

**Issue by StanczakDominik** [sc2aiur/sc2aiur.github.io#5]
There's the content template, but I'm thinking we could half-automate it via google forms or some such...

**Comment by j4np0l** [comment]
Something like Google forms would be awesome, especially for anyone who is not used to github.

**Comment by StanczakDominik** [comment]
All right, I've whipped something up at https://forms.gle/itAanDjmFkEc153u7. How does that look? @j4np0l @HappyCaterpillar

**Comment by StanczakDominik** [comment]
All right, I guess we'll be trying that and adjusting as needed!

**Comment by HappyCaterpillar** [comment]
Seems practical! I like it.
